### ISSUE TITLE
Extension not working on macos on 1.88.1

### ISSUE THREAD

**Issue by remixer-dec** [bartosz-antosik/vscode-spellright#577]
Activating extension ban.spellright failed due to an error:
2024-04-29 01:32:00.927 [error] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user/.vscode-oss/extensions/ban.spellright-3.0.124-universal/node_modules/os-locale/index.js from /Users/user/.vscode-oss/extensions/ban.spellright-3.0.124-universal/src/spellright.js not supported.
Instead change the require of index.js in /Users/user/.vscode-oss/extensions/ban.spellright-3.0.124-universal/src/spellright.js to a dynamic import() which is available in all CommonJS modules.
  
  
Version: 1.88.1
Release: 24104
Commit: 0d01a72525276e5e3771fe5851b9c83de0de1e2b
Date: 2024-04-13T01:43:30.924Z
Electron: 28.2.8
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
ОС: Darwin arm64 23.4.0

**Comment by remixer-dec** [comment]
Wrapped it with an import as suggested
```js
let osLocale
import('os-locale').then(olc => (osLocale = olc))
```
and faced another error:

> [!WARNING]  
> TypeError: glob is not a function
	at loadBinary (/Users/user/.vscode-oss/extensions/ban.spellright-3.0.124-universal/lib/bindings.js:18:21)
	at Object.<anonymous> (/Users/user/.vscode-oss/extensions/ban.spellright-3.0.124-universal/lib/bindings.js:44:12)

fixed it by changing
https://github.com/bartosz-antosik/vscode-spellright/blob/d66a383dcd851e0cdd11e2a3e993224f7e8d1caf/lib/bindings.js#L12
to 
```js
const {glob} = require("glob") 
```
and   
https://github.com/bartosz-antosik/vscode-spellright/blob/d66a383dcd851e0cdd11e2a3e993224f7e8d1caf/lib/bindings.js#L18
to
```js
  const nodeFiles = glob.sync(path.join(__dirname, `bin/${baseName}*${process.arch}*.node`), { sync: true });
```

After saving and restarting the module the extension seems to be working correctly.

**Comment by j-lakeman** [comment]
Reproduced on Debian, same VS Code version.

**Comment by AVAtarMod** [comment]
https://github.com/bartosz-antosik/vscode-spellright/issues/577#issuecomment-2081671892
> After saving and restarting the editor, the extension seems to be working correctly. 

I used this on VSCodium 1.89.1 and this works. Thanks.

OS: Linux (Fedora 39)

**Comment by Ben-Voris** [comment]
Related to #311 ?
